pipeline {
  agent any
  stages {
    
    stage("Create K8s Cluster") {
      steps {
        withAWS(region:'us-west-2', credentials:'aws-cred') {
          sh  '''
              eksctl create cluster \
              --name captsone-cluster \
              --region us-west-2 \
              --nodegroup-name standard-workers \
              --node-type t2.micro \
              --nodes 2 \
              --nodes-min 1 \
              --nodes-max 3 \
            '''
        }
      }
    }

    stage('Create conf file cluster') {
        steps {
            withAWS(region:'us-west-2', credentials:'aws-cred') {
                sh '''
                    aws eks --region us-west-2 update-kubeconfig --name captsone-cluster
                '''
            }
        }
    }

  }
}